<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('BitBag\\SyliusCmsPlugin\\Form\\Type\\BlockImageType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.block_image'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.block_image'] = new \BitBag\SyliusCmsPlugin\Form\Type\BlockImageType('BitBag\\SyliusCmsPlugin\\Entity\\BlockImage', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\BlockType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.block'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.block'] = new \BitBag\SyliusCmsPlugin\Form\Type\BlockType('BitBag\\SyliusCmsPlugin\\Entity\\Block', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\FrequentlyAskedQuestionType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.frequently_asked_question'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.frequently_asked_question'] = new \BitBag\SyliusCmsPlugin\Form\Type\FrequentlyAskedQuestionType('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestion', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\ImportType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.import'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.import'] = new \BitBag\SyliusCmsPlugin\Form\Type\ImportType());
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\MediaType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.media'] ?? $this->load('getBitbagSyliusCmsPlugin_Form_Type_MediaService.php'));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\PageImageType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.page_image'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.page_image'] = new \BitBag\SyliusCmsPlugin\Form\Type\PageImageType('BitBag\\SyliusCmsPlugin\\Entity\\PageImage', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\PageType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.page'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.page'] = new \BitBag\SyliusCmsPlugin\Form\Type\PageType('BitBag\\SyliusCmsPlugin\\Entity\\Page', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\SectionType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.section'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.section'] = new \BitBag\SyliusCmsPlugin\Form\Type\SectionType('BitBag\\SyliusCmsPlugin\\Entity\\Section', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\Translation\\BlockTranslationType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.translation.block'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.translation.block'] = new \BitBag\SyliusCmsPlugin\Form\Type\Translation\BlockTranslationType('BitBag\\SyliusCmsPlugin\\Entity\\BlockTranslation', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\Translation\\FrequentlyAskedQuestionTranslationType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.translation.frequently_asked_question'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.translation.frequently_asked_question'] = new \BitBag\SyliusCmsPlugin\Form\Type\Translation\FrequentlyAskedQuestionTranslationType('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestionTranslation', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\Translation\\MediaTranslationType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.translation.media'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.translation.media'] = new \BitBag\SyliusCmsPlugin\Form\Type\Translation\MediaTranslationType('BitBag\\SyliusCmsPlugin\\Entity\\MediaTranslation', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\Translation\\PageTranslationType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.translation.page'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.translation.page'] = new \BitBag\SyliusCmsPlugin\Form\Type\Translation\PageTranslationType('BitBag\\SyliusCmsPlugin\\Entity\\PageTranslation', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\Translation\\SectionTranslationType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.translation.section'] ?? $this->privates['bitbag_sylius_cms_plugin.form.type.translation.section'] = new \BitBag\SyliusCmsPlugin\Form\Type\Translation\SectionTranslationType('BitBag\\SyliusCmsPlugin\\Entity\\SectionTranslation', array(0 => 'bitbag')));
}, 'BitBag\\SyliusCmsPlugin\\Form\\Type\\WysiwygType' => function () {
    return ($this->privates['bitbag_sylius_cms_plugin.form.type.wysiwyg'] ?? $this->load('getBitbagSyliusCmsPlugin_Form_Type_WysiwygService.php'));
}, 'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType' => function () {
    return ($this->privates['fos_ck_editor.form.type'] ?? $this->load('getFosCkEditor_Form_TypeService.php'));
}, 'FOS\\OAuthServerBundle\\Form\\Type\\AuthorizeFormType' => function () {
    return ($this->privates['fos_oauth_server.authorize.form.type'] ?? $this->privates['fos_oauth_server.authorize.form.type'] = new \FOS\OAuthServerBundle\Form\Type\AuthorizeFormType());
}, 'Liip\\ImagineBundle\\Form\\Type\\ImageType' => function () {
    return ($this->privates['liip_imagine.form.type.image'] ?? $this->privates['liip_imagine.form.type.image'] = new \Liip\ImagineBundle\Form\Type\ImageType());
}, 'Loevgaard\\SyliusBrandPlugin\\Form\\Type\\BrandChoiceType' => function () {
    return ($this->privates['loevgaard_sylius_brand.form.type.brand_choice'] ?? $this->load('getLoevgaardSyliusBrand_Form_Type_BrandChoiceService.php'));
}, 'Loevgaard\\SyliusBrandPlugin\\Form\\Type\\BrandImageType' => function () {
    return ($this->privates['loevgaard_sylius_brand.form.type.brand_image'] ?? $this->privates['loevgaard_sylius_brand.form.type.brand_image'] = new \Loevgaard\SyliusBrandPlugin\Form\Type\BrandImageType('Loevgaard\\SyliusBrandPlugin\\Entity\\BrandImage'));
}, 'Loevgaard\\SyliusBrandPlugin\\Form\\Type\\BrandType' => function () {
    return ($this->privates['loevgaard_sylius_brand.form.type.brand'] ?? $this->privates['loevgaard_sylius_brand.form.type.brand'] = new \Loevgaard\SyliusBrandPlugin\Form\Type\BrandType('Loevgaard\\SyliusBrandPlugin\\Entity\\Brand'));
}, 'Payum\\Core\\Bridge\\Symfony\\Form\\Type\\CreditCardExpirationDateType' => function () {
    return ($this->services['payum.form.type.credit_card_expiration_date'] ?? $this->services['payum.form.type.credit_card_expiration_date'] = new \Payum\Core\Bridge\Symfony\Form\Type\CreditCardExpirationDateType());
}, 'Payum\\Core\\Bridge\\Symfony\\Form\\Type\\CreditCardType' => function () {
    return ($this->services['payum.form.type.credit_card'] ?? $this->services['payum.form.type.credit_card'] = new \Payum\Core\Bridge\Symfony\Form\Type\CreditCardType());
}, 'Payum\\Core\\Bridge\\Symfony\\Form\\Type\\GatewayConfigType' => function () {
    return ($this->services['payum.form.type.gateway_config'] ?? $this->load('getPayum_Form_Type_GatewayConfigService.php'));
}, 'Payum\\Core\\Bridge\\Symfony\\Form\\Type\\GatewayFactoriesChoiceType' => function () {
    return ($this->services['payum.form.type.gateway_factories_choice'] ?? $this->services['payum.form.type.gateway_factories_choice'] = new \Payum\Core\Bridge\Symfony\Form\Type\GatewayFactoriesChoiceType(array()));
}, 'Sonata\\BlockBundle\\Form\\Type\\ContainerTemplateType' => function () {
    return ($this->privates['sonata.block.form.type.container_template'] ?? $this->privates['sonata.block.form.type.container_template'] = new \Sonata\BlockBundle\Form\Type\ContainerTemplateType(array('@SonataBlock/Block/block_container.html.twig' => 'SonataBlockBundle default template')));
}, 'Sonata\\BlockBundle\\Form\\Type\\ServiceListType' => function () {
    return ($this->privates['sonata.block.form.type.block'] ?? $this->load('getSonata_Block_Form_Type_BlockService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\BooleanType' => function () {
    return ($this->privates['sonata.core.form.type.boolean'] ?? $this->privates['sonata.core.form.type.boolean'] = new \Sonata\CoreBundle\Form\Type\BooleanType());
}, 'Sonata\\CoreBundle\\Form\\Type\\CollectionType' => function () {
    return ($this->privates['sonata.core.form.type.collection'] ?? $this->privates['sonata.core.form.type.collection'] = new \Sonata\CoreBundle\Form\Type\CollectionType());
}, 'Sonata\\CoreBundle\\Form\\Type\\ColorSelectorType' => function () {
    return ($this->privates['sonata.core.form.type.color_selector'] ?? $this->load('getSonata_Core_Form_Type_ColorSelectorService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\ColorType' => function () {
    return ($this->privates['sonata.core.form.type.color'] ?? $this->privates['sonata.core.form.type.color'] = new \Sonata\CoreBundle\Form\Type\ColorType());
}, 'Sonata\\CoreBundle\\Form\\Type\\DatePickerType' => function () {
    return ($this->privates['sonata.core.form.type.date_picker'] ?? $this->load('getSonata_Core_Form_Type_DatePickerService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\DateRangePickerType' => function () {
    return ($this->privates['sonata.core.form.type.date_range_picker'] ?? $this->load('getSonata_Core_Form_Type_DateRangePickerService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\DateRangeType' => function () {
    return ($this->privates['sonata.core.form.type.date_range'] ?? $this->load('getSonata_Core_Form_Type_DateRangeService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\DateTimePickerType' => function () {
    return ($this->privates['sonata.core.form.type.datetime_picker'] ?? $this->load('getSonata_Core_Form_Type_DatetimePickerService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\DateTimeRangePickerType' => function () {
    return ($this->privates['sonata.core.form.type.datetime_range_picker'] ?? $this->load('getSonata_Core_Form_Type_DatetimeRangePickerService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\DateTimeRangeType' => function () {
    return ($this->privates['sonata.core.form.type.datetime_range'] ?? $this->load('getSonata_Core_Form_Type_DatetimeRangeService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\EqualType' => function () {
    return ($this->privates['sonata.core.form.type.equal'] ?? $this->load('getSonata_Core_Form_Type_EqualService.php'));
}, 'Sonata\\CoreBundle\\Form\\Type\\ImmutableArrayType' => function () {
    return ($this->privates['sonata.core.form.type.array'] ?? $this->privates['sonata.core.form.type.array'] = new \Sonata\CoreBundle\Form\Type\ImmutableArrayType());
}, 'Sonata\\CoreBundle\\Form\\Type\\TranslatableChoiceType' => function () {
    return ($this->privates['sonata.core.form.type.translatable_choice'] ?? $this->load('getSonata_Core_Form_Type_TranslatableChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\AddressType' => function () {
    return ($this->services['sylius.form.type.address'] ?? $this->load('getSylius_Form_Type_AddressService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\CountryChoiceType' => function () {
    return ($this->services['sylius.form.type.country_choice'] ?? $this->load('getSylius_Form_Type_CountryChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\CountryCodeChoiceType' => function () {
    return ($this->services['sylius.form.type.country_code_choice'] ?? $this->load('getSylius_Form_Type_CountryCodeChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\CountryType' => function () {
    return ($this->services['sylius.form.type.country'] ?? $this->load('getSylius_Form_Type_CountryService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ProvinceChoiceType' => function () {
    return ($this->services['sylius.form.type.province_choice'] ?? $this->load('getSylius_Form_Type_ProvinceChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ProvinceCodeChoiceType' => function () {
    return ($this->services['sylius.form.type.province_code_choice'] ?? $this->load('getSylius_Form_Type_ProvinceCodeChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ProvinceType' => function () {
    return ($this->services['sylius.form.type.province'] ?? $this->load('getSylius_Form_Type_ProvinceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ZoneChoiceType' => function () {
    return ($this->services['sylius.form.type.zone_choice'] ?? $this->load('getSylius_Form_Type_ZoneChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ZoneCodeChoiceType' => function () {
    return ($this->services['sylius.form.type.zone_code_choice'] ?? $this->load('getSylius_Form_Type_ZoneCodeChoiceService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ZoneMemberType' => function () {
    return ($this->services['sylius.form.type.zone_member'] ?? $this->load('getSylius_Form_Type_ZoneMemberService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\ZoneType' => function () {
    return ($this->services['sylius.form.type.zone'] ?? $this->load('getSylius_Form_Type_ZoneService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\AddressType' => function () {
    return ($this->services['sylius.form.type.api_checkout_address'] ?? $this->services['sylius.form.type.api_checkout_address'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\AddressType());
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\ClientType' => function () {
    return ($this->services['sylius.form.type.api_client'] ?? $this->load('getSylius_Form_Type_ApiClientService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\CustomerProfileType' => function () {
    return ($this->services['sylius.form.type.api_customer'] ?? $this->load('getSylius_Form_Type_ApiCustomerService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\OrderItemType' => function () {
    return ($this->services['sylius.form.type.api_order_item'] ?? $this->load('getSylius_Form_Type_ApiOrderItemService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\OrderPromotionCouponType' => function () {
    return ($this->services['sylius.form.type.api_order_promotion_coupon'] ?? $this->load('getSylius_Form_Type_ApiOrderPromotionCouponService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\OrderType' => function () {
    return ($this->services['sylius.form.type.api_order'] ?? $this->load('getSylius_Form_Type_ApiOrderService.php'));
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\ProductType' => function () {
    return ($this->services['sylius.form.type.api_product'] ?? $this->services['sylius.form.type.api_product'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\ProductType());
}, 'Sylius\\Bundle\\AdminApiBundle\\Form\\Type\\ProductVariantType' => function () {
    return ($this->services['sylius.form.type.api_product_variant'] ?? $this->services['sylius.form.type.api_product_variant'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\ProductVariantType());
}, 'Sylius\\Bundle\\AttributeBundle\\Form\\Type\\AttributeTypeChoiceType' => function () {
    return ($this->services['sylius.form.type.attribute_type_choice'] ?? $this->load('getSylius_Form_Type_AttributeTypeChoiceService.php'));
}, 'Sylius\\Bundle\\AttributeBundle\\Form\\Type\\AttributeType\\Configuration\\SelectAttributeChoicesCollectionType' => function () {
    return ($this->services['sylius.form.type.attribute_type.select.choices_collection'] ?? $this->load('getSylius_Form_Type_AttributeType_Select_ChoicesCollectionService.php'));
}, 'Sylius\\Bundle\\AttributeBundle\\Form\\Type\\AttributeType\\Configuration\\SelectAttributeValueTranslationsType' => function () {
    return ($this->services['sylius.attribute_type.select.value.translations'] ?? $this->load('getSylius_AttributeType_Select_Value_TranslationsService.php'));
}, 'Sylius\\Bundle\\AttributeBundle\\Form\\Type\\AttributeType\\SelectAttributeType' => function () {
    return ($this->services['sylius.form.type.attribute_type.select'] ?? $this->load('getSylius_Form_Type_AttributeType_SelectService.php'));
}, 'Sylius\\Bundle\\ChannelBundle\\Form\\Type\\ChannelChoiceType' => function () {
    return ($this->services['sylius.form.type.channel_choice'] ?? $this->load('getSylius_Form_Type_ChannelChoiceService.php'));
}, 'Sylius\\Bundle\\ChannelBundle\\Form\\Type\\ChannelType' => function () {
    return ($this->services['sylius.form.type.channel'] ?? $this->load('getSylius_Form_Type_ChannelService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\AddressChoiceType' => function () {
    return ($this->services['sylius.form.type.address_choice'] ?? $this->load('getSylius_Form_Type_AddressChoiceService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\ChannelCollectionType' => function () {
    return ($this->services['sylius.form.type.channels_collection'] ?? $this->load('getSylius_Form_Type_ChannelsCollectionService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\AddressType' => function () {
    return ($this->services['sylius.form.type.checkout_address'] ?? $this->load('getSylius_Form_Type_CheckoutAddressService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\CompleteType' => function () {
    return ($this->services['sylius.form.type.checkout_complete'] ?? $this->load('getSylius_Form_Type_CheckoutCompleteService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\PaymentType' => function () {
    return ($this->services['sylius.form.type.checkout_payment'] ?? $this->load('getSylius_Form_Type_CheckoutPaymentService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\SelectPaymentType' => function () {
    return ($this->services['sylius.form.type.checkout_select_payment'] ?? $this->load('getSylius_Form_Type_CheckoutSelectPaymentService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\SelectShippingType' => function () {
    return ($this->services['sylius.form.type.checkout_select_shipping'] ?? $this->load('getSylius_Form_Type_CheckoutSelectShippingService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Checkout\\ShipmentType' => function () {
    return ($this->services['sylius.form.type.checkout_shipment'] ?? $this->load('getSylius_Form_Type_CheckoutShipmentService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Customer\\CustomerGuestType' => function () {
    return ($this->services['sylius.form.type.customer_guest'] ?? $this->load('getSylius_Form_Type_CustomerGuestService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Customer\\CustomerRegistrationType' => function () {
    return ($this->services['sylius.form.type.customer_registration'] ?? $this->load('getSylius_Form_Type_CustomerRegistrationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Customer\\CustomerSimpleRegistrationType' => function () {
    return ($this->services['sylius.form.type.customer_simple_registration'] ?? $this->load('getSylius_Form_Type_CustomerSimpleRegistrationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Order\\AddToCartType' => function () {
    return ($this->services['sylius.form.type.add_to_cart'] ?? $this->load('getSylius_Form_Type_AddToCartService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Product\\ChannelPricingType' => function () {
    return ($this->services['sylius.form.type.channel_pricing'] ?? $this->load('getSylius_Form_Type_ChannelPricingService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Product\\ProductImageType' => function () {
    return ($this->services['sylius.form.type.product_image'] ?? $this->load('getSylius_Form_Type_ProductImageService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Product\\ProductReviewType' => function () {
    return ($this->services['sylius.form.type.product_review'] ?? $this->load('getSylius_Form_Type_ProductReviewService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Filter\\ProductFilterConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_action.filter.product'] ?? $this->load('getSylius_Form_Type_PromotionAction_Filter_ProductService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Filter\\TaxonFilterConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_action.filter.taxon'] ?? $this->load('getSylius_Form_Type_PromotionAction_Filter_TaxonService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ContainsProductConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_rule.contains_product_configuration'] ?? $this->load('getSylius_Form_Type_PromotionRule_ContainsProductConfigurationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\CustomerGroupConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_rule.customer_group_configuration'] ?? $this->services['sylius.form.type.promotion_rule.customer_group_configuration'] = new \Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\CustomerGroupConfigurationType());
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\HasTaxonConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_rule.has_taxon_configuration'] ?? $this->load('getSylius_Form_Type_PromotionRule_HasTaxonConfigurationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\TotalOfItemsFromTaxonConfigurationType' => function () {
    return ($this->services['sylius.form.type.promotion_rule.total_of_items_from_taxon_configuration'] ?? $this->load('getSylius_Form_Type_PromotionRule_TotalOfItemsFromTaxonConfigurationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Shipping\\Calculator\\ChannelBasedFlatRateConfigurationType' => function () {
    return ($this->services['sylius.form.type.channel_based_shipping_calculator.flat_rate'] ?? $this->services['sylius.form.type.channel_based_shipping_calculator.flat_rate'] = new \Sylius\Bundle\CoreBundle\Form\Type\Shipping\Calculator\ChannelBasedFlatRateConfigurationType());
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Shipping\\Calculator\\ChannelBasedPerUnitRateConfigurationType' => function () {
    return ($this->services['sylius.form.type.channel_based_shipping_calculator.per_unit_rate'] ?? $this->services['sylius.form.type.channel_based_shipping_calculator.per_unit_rate'] = new \Sylius\Bundle\CoreBundle\Form\Type\Shipping\Calculator\ChannelBasedPerUnitRateConfigurationType());
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\TaxCalculationStrategyChoiceType' => function () {
    return ($this->services['sylius.form.type.tax_calculation_strategy_choice'] ?? $this->load('getSylius_Form_Type_TaxCalculationStrategyChoiceService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Taxon\\ProductTaxonAutocompleteChoiceType' => function () {
    return ($this->services['sylius.form.type.autocomplete_product_taxon_choice'] ?? $this->load('getSylius_Form_Type_AutocompleteProductTaxonChoiceService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Taxon\\TaxonImageType' => function () {
    return ($this->services['sylius.form.type.taxon_image'] ?? $this->services['sylius.form.type.taxon_image'] = new \Sylius\Bundle\CoreBundle\Form\Type\Taxon\TaxonImageType('Sylius\\Component\\Core\\Model\\TaxonImage'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\User\\AdminUserType' => function () {
    return ($this->services['sylius.form.type.admin_user'] ?? $this->load('getSylius_Form_Type_AdminUserService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\User\\ShopUserRegistrationType' => function () {
    return ($this->services['sylius.form.type.shop_user_registration'] ?? $this->load('getSylius_Form_Type_ShopUserRegistrationService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\User\\ShopUserType' => function () {
    return ($this->services['sylius.form.type.shop_user'] ?? $this->load('getSylius_Form_Type_ShopUserService.php'));
}, 'Sylius\\Bundle\\CurrencyBundle\\Form\\Type\\CurrencyChoiceType' => function () {
    return ($this->services['sylius.form.type.currency_choice'] ?? $this->load('getSylius_Form_Type_CurrencyChoiceService.php'));
}, 'Sylius\\Bundle\\CurrencyBundle\\Form\\Type\\CurrencyType' => function () {
    return ($this->services['sylius.form.type.currency'] ?? $this->load('getSylius_Form_Type_CurrencyService.php'));
}, 'Sylius\\Bundle\\CurrencyBundle\\Form\\Type\\ExchangeRateType' => function () {
    return ($this->services['sylius.form.type.exchange_rate'] ?? $this->load('getSylius_Form_Type_ExchangeRateService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerChoiceType' => function () {
    return ($this->services['sylius.form.type.customer_choice'] ?? $this->load('getSylius_Form_Type_CustomerChoiceService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerGroupChoiceType' => function () {
    return ($this->services['sylius.form.type.customer_group_choice'] ?? $this->load('getSylius_Form_Type_CustomerGroupChoiceService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerGroupCodeChoiceType' => function () {
    return ($this->services['sylius.form.type.customer_group_code_choice'] ?? $this->load('getSylius_Form_Type_CustomerGroupCodeChoiceService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerGroupType' => function () {
    return ($this->services['sylius.form.type.customer_group'] ?? $this->load('getSylius_Form_Type_CustomerGroupService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerProfileType' => function () {
    return ($this->services['sylius.form.type.customer_profile'] ?? $this->load('getSylius_Form_Type_CustomerProfileService.php'));
}, 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerType' => function () {
    return ($this->services['sylius.form.type.customer'] ?? $this->load('getSylius_Form_Type_CustomerService.php'));
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\BooleanFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.boolean'] ?? $this->services['sylius.form.type.grid_filter.boolean'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\BooleanFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\DateFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.date'] ?? $this->services['sylius.form.type.grid_filter.date'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\DateFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\EntityFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.entity'] ?? $this->services['sylius.form.type.grid_filter.entity'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\EntityFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\ExistsFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.exists'] ?? $this->services['sylius.form.type.grid_filter.exists'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\ExistsFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\MoneyFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.money'] ?? $this->services['sylius.form.type.grid_filter.money'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\MoneyFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\StringFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.string'] ?? $this->services['sylius.form.type.grid_filter.string'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\StringFilterType());
}, 'Sylius\\Bundle\\LocaleBundle\\Form\\Type\\LocaleChoiceType' => function () {
    return ($this->services['sylius.form.type.locale_choice'] ?? $this->load('getSylius_Form_Type_LocaleChoiceService.php'));
}, 'Sylius\\Bundle\\LocaleBundle\\Form\\Type\\LocaleType' => function () {
    return ($this->services['sylius.form.type.locale'] ?? $this->load('getSylius_Form_Type_LocaleService.php'));
}, 'Sylius\\Bundle\\MoneyBundle\\Form\\Type\\MoneyType' => function () {
    return ($this->services['sylius.form.type.money'] ?? $this->services['sylius.form.type.money'] = new \Sylius\Bundle\MoneyBundle\Form\Type\MoneyType());
}, 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\CartItemType' => function () {
    return ($this->services['sylius.form.type.cart_item'] ?? $this->load('getSylius_Form_Type_CartItemService.php'));
}, 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\CartType' => function () {
    return ($this->services['sylius.form.type.cart'] ?? $this->load('getSylius_Form_Type_CartService.php'));
}, 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\OrderItemType' => function () {
    return ($this->services['sylius.form.type.order_item'] ?? $this->load('getSylius_Form_Type_OrderItemService.php'));
}, 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\OrderType' => function () {
    return ($this->services['sylius.form.type.order'] ?? $this->load('getSylius_Form_Type_OrderService.php'));
}, 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentGatewayChoiceType' => function () {
    return ($this->services['sylius.form.type.payment_gateway_choice'] ?? $this->load('getSylius_Form_Type_PaymentGatewayChoiceService.php'));
}, 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentMethodChoiceType' => function () {
    return ($this->services['sylius.form.type.payment_method_choice'] ?? $this->load('getSylius_Form_Type_PaymentMethodChoiceService.php'));
}, 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentMethodTranslationType' => function () {
    return ($this->services['sylius.form.type.payment_method_translation'] ?? $this->load('getSylius_Form_Type_PaymentMethodTranslationService.php'));
}, 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentMethodType' => function () {
    return ($this->services['sylius.form.type.payment_method'] ?? $this->load('getSylius_Form_Type_PaymentMethodService.php'));
}, 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentType' => function () {
    return ($this->services['sylius.form.type.payment'] ?? $this->load('getSylius_Form_Type_PaymentService.php'));
}, 'Sylius\\Bundle\\PayumBundle\\Form\\Type\\GatewayConfigType' => function () {
    return ($this->services['sylius.form.type.gateway_config'] ?? $this->load('getSylius_Form_Type_GatewayConfigService.php'));
}, 'Sylius\\Bundle\\PayumBundle\\Form\\Type\\PaypalGatewayConfigurationType' => function () {
    return ($this->services['sylius.form.type.gateway_configuration.paypal'] ?? $this->services['sylius.form.type.gateway_configuration.paypal'] = new \Sylius\Bundle\PayumBundle\Form\Type\PaypalGatewayConfigurationType());
}, 'Sylius\\Bundle\\PayumBundle\\Form\\Type\\StripeGatewayConfigurationType' => function () {
    return ($this->services['sylius.form.type.gateway_configuration.stripe'] ?? $this->services['sylius.form.type.gateway_configuration.stripe'] = new \Sylius\Bundle\PayumBundle\Form\Type\StripeGatewayConfigurationType());
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAssociationType' => function () {
    return ($this->services['sylius.form.type.product_association'] ?? $this->load('getSylius_Form_Type_ProductAssociationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAssociationTypeChoiceType' => function () {
    return ($this->services['sylius.form.type.product_association_type_choice'] ?? $this->load('getSylius_Form_Type_ProductAssociationTypeChoiceService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAssociationTypeTranslationType' => function () {
    return ($this->services['sylius.form.type.product_association_type_translation'] ?? $this->load('getSylius_Form_Type_ProductAssociationTypeTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAssociationTypeType' => function () {
    return ($this->services['sylius.form.type.product_association_type'] ?? $this->load('getSylius_Form_Type_ProductAssociationTypeService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAssociationsType' => function () {
    return ($this->services['sylius.form.type.sylius_product_associations'] ?? $this->load('getSylius_Form_Type_SyliusProductAssociationsService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAttributeChoiceType' => function () {
    return ($this->services['sylius.form.type.product_attribute_choice'] ?? $this->load('getSylius_Form_Type_ProductAttributeChoiceService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAttributeTranslationType' => function () {
    return ($this->services['sylius.form.type.product_attribute_translation'] ?? $this->load('getSylius_Form_Type_ProductAttributeTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAttributeType' => function () {
    return ($this->services['sylius.form.type.product_attribute'] ?? $this->load('getSylius_Form_Type_ProductAttributeService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAttributeValueType' => function () {
    return ($this->services['sylius.form.type.product_attribute_value'] ?? $this->load('getSylius_Form_Type_ProductAttributeValueService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductChoiceType' => function () {
    return ($this->services['sylius.form.type.product_choice'] ?? $this->load('getSylius_Form_Type_ProductChoiceService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductCodeChoiceType' => function () {
    return ($this->services['sylius.form.type.product_code_choice'] ?? $this->load('getSylius_Form_Type_ProductCodeChoiceService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductGenerateVariantsType' => function () {
    return ($this->services['sylius.form.type.product_generate_variants'] ?? $this->load('getSylius_Form_Type_ProductGenerateVariantsService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductOptionChoiceType' => function () {
    return ($this->services['sylius.form.type.product_option_choice'] ?? $this->load('getSylius_Form_Type_ProductOptionChoiceService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductOptionTranslationType' => function () {
    return ($this->services['sylius.form.type.product_option_translation'] ?? $this->load('getSylius_Form_Type_ProductOptionTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductOptionType' => function () {
    return ($this->services['sylius.form.type.product_option'] ?? $this->load('getSylius_Form_Type_ProductOptionService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductOptionValueTranslationType' => function () {
    return ($this->services['sylius.form.type.product_option_value_translation'] ?? $this->load('getSylius_Form_Type_ProductOptionValueTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductOptionValueType' => function () {
    return ($this->services['sylius.form.type.product_option_value'] ?? $this->load('getSylius_Form_Type_ProductOptionValueService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductTranslationType' => function () {
    return ($this->services['sylius.form.type.product_translation'] ?? $this->load('getSylius_Form_Type_ProductTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductType' => function () {
    return ($this->services['sylius.form.type.product'] ?? $this->load('getSylius_Form_Type_ProductService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantGenerationType' => function () {
    return ($this->services['sylius.form.type.product_variant_generation'] ?? $this->load('getSylius_Form_Type_ProductVariantGenerationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantTranslationType' => function () {
    return ($this->services['sylius.form.type.product_variant_translation'] ?? $this->load('getSylius_Form_Type_ProductVariantTranslationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantType' => function () {
    return ($this->services['sylius.form.type.product_variant'] ?? $this->load('getSylius_Form_Type_ProductVariantService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionActionChoiceType' => function () {
    return ($this->services['sylius.form.type.promotion_action_choice'] ?? $this->load('getSylius_Form_Type_PromotionActionChoiceService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionActionCollectionType' => function () {
    return ($this->services['sylius.form.type.promotion_action.collection'] ?? $this->load('getSylius_Form_Type_PromotionAction_CollectionService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionActionType' => function () {
    return ($this->services['sylius.form.type.promotion_action'] ?? $this->load('getSylius_Form_Type_PromotionActionService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionCouponGeneratorInstructionType' => function () {
    return ($this->services['sylius.form.type.promotion_coupon_generator_instruction'] ?? $this->services['sylius.form.type.promotion_coupon_generator_instruction'] = new \Sylius\Bundle\PromotionBundle\Form\Type\PromotionCouponGeneratorInstructionType('Sylius\\Component\\Promotion\\Generator\\PromotionCouponGeneratorInstruction'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionCouponToCodeType' => function () {
    return ($this->services['sylius.form.type.promotion_coupon_to_code'] ?? $this->load('getSylius_Form_Type_PromotionCouponToCodeService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionCouponType' => function () {
    return ($this->services['sylius.form.type.promotion_coupon'] ?? $this->load('getSylius_Form_Type_PromotionCouponService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionRuleChoiceType' => function () {
    return ($this->services['sylius.form.type.promotion_rule_choice'] ?? $this->load('getSylius_Form_Type_PromotionRuleChoiceService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionRuleCollectionType' => function () {
    return ($this->services['sylius.form.type.promotion_rule.collection'] ?? $this->load('getSylius_Form_Type_PromotionRule_CollectionService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionRuleType' => function () {
    return ($this->services['sylius.form.type.promotion_rule'] ?? $this->load('getSylius_Form_Type_PromotionRuleService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionType' => function () {
    return ($this->services['sylius.form.type.promotion'] ?? $this->load('getSylius_Form_Type_PromotionService.php'));
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\DefaultResourceType' => function () {
    return ($this->services['sylius.form.type.default'] ?? $this->load('getSylius_Form_Type_DefaultService.php'));
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\ResourceAutocompleteChoiceType' => function () {
    return ($this->services['sylius.form.type.resource_autocomplete_choice'] ?? $this->load('getSylius_Form_Type_ResourceAutocompleteChoiceService.php'));
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\ResourceTranslationsType' => function () {
    return ($this->services['sylius.form.type.resource_translations'] ?? $this->load('getSylius_Form_Type_ResourceTranslationsService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\CalculatorChoiceType' => function () {
    return ($this->services['sylius.form.type.shipping_calculator_choice'] ?? $this->load('getSylius_Form_Type_ShippingCalculatorChoiceService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShipmentShipType' => function () {
    return ($this->services['sylius.form.type.shipment_ship'] ?? $this->load('getSylius_Form_Type_ShipmentShipService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShipmentType' => function () {
    return ($this->services['sylius.form.type.shipment'] ?? $this->load('getSylius_Form_Type_ShipmentService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingCategoryChoiceType' => function () {
    return ($this->services['sylius.form.type.shipping_category_choice'] ?? $this->load('getSylius_Form_Type_ShippingCategoryChoiceService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingCategoryType' => function () {
    return ($this->services['sylius.form.type.shipping_category'] ?? $this->load('getSylius_Form_Type_ShippingCategoryService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingMethodChoiceType' => function () {
    return ($this->services['sylius.form.type.shipping_method_choice'] ?? $this->load('getSylius_Form_Type_ShippingMethodChoiceService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingMethodTranslationType' => function () {
    return ($this->services['sylius.form.type.shipping_method_translation'] ?? $this->load('getSylius_Form_Type_ShippingMethodTranslationService.php'));
}, 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingMethodType' => function () {
    return ($this->services['sylius.form.type.shipping_method'] ?? $this->load('getSylius_Form_Type_ShippingMethodService.php'));
}, 'Sylius\\Bundle\\TaxationBundle\\Form\\Type\\TaxCalculatorChoiceType' => function () {
    return ($this->services['sylius.form.type.tax_calculator_choice'] ?? $this->load('getSylius_Form_Type_TaxCalculatorChoiceService.php'));
}, 'Sylius\\Bundle\\TaxationBundle\\Form\\Type\\TaxCategoryChoiceType' => function () {
    return ($this->services['sylius.form.type.tax_category_choice'] ?? $this->load('getSylius_Form_Type_TaxCategoryChoiceService.php'));
}, 'Sylius\\Bundle\\TaxationBundle\\Form\\Type\\TaxCategoryType' => function () {
    return ($this->services['sylius.form.type.tax_category'] ?? $this->load('getSylius_Form_Type_TaxCategoryService.php'));
}, 'Sylius\\Bundle\\TaxationBundle\\Form\\Type\\TaxRateType' => function () {
    return ($this->services['sylius.form.type.tax_rate'] ?? $this->load('getSylius_Form_Type_TaxRateService.php'));
}, 'Sylius\\Bundle\\TaxonomyBundle\\Form\\Type\\TaxonPositionType' => function () {
    return ($this->services['sylius.form.type.taxon_position'] ?? $this->load('getSylius_Form_Type_TaxonPositionService.php'));
}, 'Sylius\\Bundle\\TaxonomyBundle\\Form\\Type\\TaxonTranslationType' => function () {
    return ($this->services['sylius.form.type.taxon_translation'] ?? $this->load('getSylius_Form_Type_TaxonTranslationService.php'));
}, 'Sylius\\Bundle\\TaxonomyBundle\\Form\\Type\\TaxonType' => function () {
    return ($this->services['sylius.form.type.taxon'] ?? $this->load('getSylius_Form_Type_TaxonService.php'));
}, 'Sylius\\Bundle\\ThemeBundle\\Form\\Type\\ThemeChoiceType' => function () {
    return ($this->services['sylius.theme.form.type.theme_choice'] ?? $this->load('getSylius_Theme_Form_Type_ThemeChoiceService.php'));
}, 'Sylius\\Bundle\\ThemeBundle\\Form\\Type\\ThemeNameChoiceType' => function () {
    return ($this->services['sylius.theme.form.type.theme_name_choice'] ?? $this->load('getSylius_Theme_Form_Type_ThemeNameChoiceService.php'));
}, 'Sylius\\Bundle\\UiBundle\\Form\\Type\\SecurityLoginType' => function () {
    return ($this->services['sylius.form.type.security_login'] ?? $this->services['sylius.form.type.security_login'] = new \Sylius\Bundle\UiBundle\Form\Type\SecurityLoginType());
}, 'Sylius\\Bundle\\UserBundle\\Form\\Type\\UserChangePasswordType' => function () {
    return ($this->services['sylius.form.type.user_change_password'] ?? $this->load('getSylius_Form_Type_UserChangePasswordService.php'));
}, 'Sylius\\Bundle\\UserBundle\\Form\\Type\\UserLoginType' => function () {
    return ($this->services['sylius.form.type.user_login'] ?? $this->services['sylius.form.type.user_login'] = new \Sylius\Bundle\UserBundle\Form\Type\UserLoginType());
}, 'Sylius\\Bundle\\UserBundle\\Form\\Type\\UserRequestPasswordResetType' => function () {
    return ($this->services['sylius.form.type.user_request_password_reset'] ?? $this->load('getSylius_Form_Type_UserRequestPasswordResetService.php'));
}, 'Sylius\\Bundle\\UserBundle\\Form\\Type\\UserResetPasswordType' => function () {
    return ($this->services['sylius.form.type.user_reset_password'] ?? $this->load('getSylius_Form_Type_UserResetPasswordService.php'));
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load('getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load('getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load('getForm_Type_FormService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 1 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 2 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 4), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? $this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? $this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
}, 1), 'Sylius\\Bundle\\AddressingBundle\\Form\\Type\\CountryType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.country'] ?? $this->load('getSylius_Form_Extension_Type_CountryService.php'));
}, 1), 'Sylius\\Bundle\\ChannelBundle\\Form\\Type\\ChannelType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.channel'] ?? $this->load('getSylius_Form_Extension_Type_ChannelService.php'));
}, 1), 'Sylius\\Bundle\\LocaleBundle\\Form\\Type\\LocaleType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.locale'] ?? $this->load('getSylius_Form_Extension_Type_LocaleService.php'));
}, 1), 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\OrderType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.order'] ?? $this->services['sylius.form.extension.type.order'] = new \Sylius\Bundle\CoreBundle\Form\Extension\OrderTypeExtension());
}, 1), 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\CartType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.cart'] ?? $this->services['sylius.form.extension.type.cart'] = new \Sylius\Bundle\CoreBundle\Form\Extension\CartTypeExtension());
}, 1), 'Sylius\\Bundle\\OrderBundle\\Form\\Type\\CartItemType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.cart_item'] ?? $this->services['sylius.form.extension.type.cart_item'] = new \Sylius\Bundle\CoreBundle\Form\Extension\CartItemTypeExtension());
}, 1), 'Sylius\\Bundle\\PaymentBundle\\Form\\Type\\PaymentMethodType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.payment_method'] ?? $this->services['sylius.form.extension.type.payment_method'] = new \Sylius\Bundle\CoreBundle\Form\Extension\PaymentMethodTypeExtension());
}, 1), 'Sylius\\Bundle\\TaxationBundle\\Form\\Type\\TaxRateType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.tax_rate'] ?? $this->services['sylius.form.extension.type.tax_rate'] = new \Sylius\Bundle\CoreBundle\Form\Extension\TaxRateTypeExtension());
}, 1), 'Sylius\\Bundle\\TaxonomyBundle\\Form\\Type\\TaxonType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.taxon'] ?? $this->services['sylius.form.extension.type.taxon'] = new \Sylius\Bundle\CoreBundle\Form\Extension\TaxonTypeExtension());
}, 1), 'Sylius\\Bundle\\CustomerBundle\\Form\\Type\\CustomerType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.customer'] ?? $this->services['sylius.form.extension.type.customer'] = new \Sylius\Bundle\CoreBundle\Form\Extension\CustomerTypeExtension());
}, 1), 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.promotion'] ?? $this->services['sylius.form.extension.type.promotion'] = new \Sylius\Bundle\CoreBundle\Form\Extension\PromotionTypeExtension());
}, 1), 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionCouponType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.promotion_coupon'] ?? $this->services['sylius.form.extension.type.promotion_coupon'] = new \Sylius\Bundle\CoreBundle\Form\Extension\PromotionCouponTypeExtension());
}, 1), 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\PromotionFilterCollectionType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.promotion_filter_collection'] ?? $this->services['sylius.form.extension.type.promotion_filter_collection'] = new \Sylius\Bundle\CoreBundle\Form\Extension\PromotionFilterCollectionTypeExtension());
}, 1), 'Sylius\\Bundle\\ShippingBundle\\Form\\Type\\ShippingMethodType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.shipping_method'] ?? $this->services['sylius.form.extension.type.shipping_method'] = new \Sylius\Bundle\CoreBundle\Form\Extension\ShippingMethodTypeExtension());
}, 1), 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.product'] ?? $this->services['sylius.form.extension.type.product'] = new \Sylius\Bundle\CoreBundle\Form\Extension\ProductTypeExtension());
    yield 1 => ($this->privates['loevgaard_sylius_brand.form.extension.type.product'] ?? $this->privates['loevgaard_sylius_brand.form.extension.type.product'] = new \Loevgaard\SyliusBrandPlugin\Form\Extension\ProductTypeExtension('Loevgaard\\SyliusBrandPlugin\\Entity\\Brand'));
}, 2), 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductTranslationType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.product_translation'] ?? $this->services['sylius.form.extension.type.product_translation'] = new \Sylius\Bundle\CoreBundle\Form\Extension\ProductTranslationTypeExtension());
}, 1), 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.product_variant'] ?? $this->services['sylius.form.extension.type.product_variant'] = new \Sylius\Bundle\CoreBundle\Form\Extension\ProductVariantTypeExtension());
}, 1), 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantGenerationType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.product_variant_generation'] ?? $this->services['sylius.form.extension.type.product_variant_generation'] = new \Sylius\Bundle\CoreBundle\Form\Extension\ProductVariantGenerationTypeExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\CollectionType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.collection'] ?? $this->services['sylius.form.extension.type.collection'] = new \Sylius\Bundle\ResourceBundle\Form\Extension\CollectionTypeExtension());
}, 1), 'Payum\\Core\\Bridge\\Symfony\\Form\\Type\\GatewayFactoriesChoiceType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['payum.form.extension.gateway_factories_choice'] ?? $this->load('getPayum_Form_Extension_GatewayFactoriesChoiceService.php'));
}, 1), 'Sylius\\Bundle\\PayumBundle\\Form\\Type\\GatewayConfigType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.gateway_config.crypted'] ?? $this->services['sylius.form.extension.type.gateway_config.crypted'] = new \Sylius\Bundle\PayumBundle\Form\Extension\CryptedGatewayConfigTypeExtension(NULL));
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))), ($this->privates['form.resolved_type_factory'] ?? $this->privates['form.resolved_type_factory'] = new \Symfony\Component\Form\ResolvedFormTypeFactory()));
