<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hateoas.generator.registry' shared service.

include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/UrlGenerator/UrlGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/UrlGenerator/SymfonyUrlGenerator.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/UrlGenerator/UrlGeneratorRegistry.php';

return $this->services['hateoas.generator.registry'] = new \Hateoas\UrlGenerator\UrlGeneratorRegistry(new \Hateoas\UrlGenerator\SymfonyUrlGenerator(($this->services['router'] ?? $this->getRouterService())));
