<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.expression.evaluator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/ExpressionLanguage/ExpressionLanguage.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas-bundle/ExpressionLanguage/ExpressionLanguage.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/Expression/ExpressionEvaluator.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas-bundle/Hateoas/Expression/LazyFunctionExpressionEvaluator.php';

$this->privates['hateoas.expression.evaluator'] = $instance = new \Bazinga\Bundle\HateoasBundle\Hateoas\Expression\LazyFunctionExpressionEvaluator(new \Bazinga\Bundle\HateoasBundle\ExpressionLanguage\ExpressionLanguage(), array(), $this);

$instance->setContextVariable('container', $this);
$instance->registerFunctionId('hateoas.expression.link');

return $instance;
