<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knp_gaufrette.filesystem_map' shared service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-gaufrette-bundle/FilesystemMap.php';

return $this->services['knp_gaufrette.filesystem_map'] = new \Knp\Bundle\GaufretteBundle\FilesystemMap(array('sylius_image' => ($this->services['gaufrette.sylius_image_filesystem'] ?? $this->load('getGaufrette_SyliusImageFilesystemService.php')), 'bitbag_sylius_cms_plugin_media' => ($this->services['gaufrette.bitbag_sylius_cms_plugin_media_filesystem'] ?? $this->load('getGaufrette_BitbagSyliusCmsPluginMediaFilesystemService.php'))));
