<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_imagine.cache.resolver.default' shared service.

include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Imagine/Cache/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Imagine/Cache/Resolver/WebPathResolver.php';

return $this->services['liip_imagine.cache.resolver.default'] = new \Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver(($this->services['filesystem'] ?? $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()), ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()), ($this->targetDirs[3].'/web'), 'media/cache');
