<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.profiler.payum_collector' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php';
include_once $this->targetDirs[3].'/vendor/payum/payum/src/Payum/Core/Extension/ExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/payum/payum-bundle/Profiler/PayumCollector.php';

return $this->services['payum.profiler.payum_collector'] = new \Payum\Bundle\PayumBundle\Profiler\PayumCollector();
