<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.validator.customer_initializer' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ObjectInitializerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Initializer/CustomerInitializer.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Canonicalizer/CanonicalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Canonicalizer/Canonicalizer.php';

return $this->services['sylius.validator.customer_initializer'] = new \Sylius\Bundle\CoreBundle\Validator\Initializer\CustomerInitializer(($this->services['sylius.canonicalizer'] ?? $this->services['sylius.canonicalizer'] = new \Sylius\Component\User\Canonicalizer\Canonicalizer()));
