<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid_field.datetime' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Grid/FieldTypes/FieldTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Grid/FieldTypes/DatetimeFieldType.php';

return $this->services['sylius.grid_field.datetime'] = new \Sylius\Component\Grid\FieldTypes\DatetimeFieldType(($this->services['sylius.grid.data_extractor.property_access'] ?? $this->load('getSylius_Grid_DataExtractor_PropertyAccessService.php')));
