<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.checkout_steps' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Templating/Helper/CheckoutStepsHelper.php';

if ($lazyLoad) {
    return $this->services['sylius.templating.helper.checkout_steps'] = $this->createProxy('CheckoutStepsHelper_87a88b2', function () {
        return \CheckoutStepsHelper_87a88b2::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSylius_Templating_Helper_CheckoutStepsService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Sylius\Bundle\CoreBundle\Templating\Helper\CheckoutStepsHelper(($this->services['sylius.checker.order_payment_method_selection_requirement'] ?? $this->load('getSylius_Checker_OrderPaymentMethodSelectionRequirementService.php')), ($this->services['sylius.checker.order_shipping_method_selection_requirement'] ?? $this->load('getSylius_Checker_OrderShippingMethodSelectionRequirementService.php')));
