<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.intl.timezone_detector.locale' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/intl-bundle/src/Timezone/TimezoneDetectorInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/intl-bundle/src/Timezone/LocaleBasedTimezoneDetector.php';

return $this->services['sonata.intl.timezone_detector.locale'] = new \Sonata\IntlBundle\Timezone\LocaleBasedTimezoneDetector(($this->services['sonata.intl.locale_detector.request_stack'] ?? $this->load('getSonata_Intl_LocaleDetector_RequestStackService.php')), array());
