<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.block.context_manager.default' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Block/BlockLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Block/Loader/ServiceLoader.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Block/BlockLoaderChain.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Block/BlockContextManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Block/BlockContextManager.php';

$this->services['sonata.block.context_manager.default'] = $instance = new \Sonata\BlockBundle\Block\BlockContextManager(new \Sonata\BlockBundle\Block\BlockLoaderChain(array(0 => new \Sonata\BlockBundle\Block\Loader\ServiceLoader(array(0 => 'sonata.block.service.template')))), ($this->services['sonata.block.manager'] ?? $this->load('getSonata_Block_ManagerService.php')), $this->parameters['sonata_block.cache_blocks'], ($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php')));

$instance->addSettingsByType('sonata.block.service.template', array('address' => NULL, 'addresses' => NULL, 'cart' => NULL, 'channel' => NULL, 'customer' => NULL, 'form' => NULL, 'order' => NULL, 'order_item' => NULL, 'orders' => NULL, 'product' => NULL, 'product_review' => NULL, 'product_reviews' => NULL, 'products' => NULL, 'resource' => NULL, 'resources' => NULL, 'statistics' => NULL, 'taxon' => NULL), true);

return $instance;
