<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.inventory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/InventoryBundle/Templating/Helper/InventoryHelper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Inventory/Checker/AvailabilityCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Inventory/Checker/AvailabilityChecker.php';

return $this->services['sylius.templating.helper.inventory'] = new \Sylius\Bundle\InventoryBundle\Templating\Helper\InventoryHelper(($this->services['sylius.availability_checker.default'] ?? $this->services['sylius.availability_checker.default'] = new \Sylius\Component\Inventory\Checker\AvailabilityChecker()));
