<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.money_formatter' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatter.php';

return $this->services['sylius.money_formatter'] = new \Sylius\Bundle\MoneyBundle\Formatter\MoneyFormatter();
