<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.adjustments_aggregator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Aggregator/AdjustmentsAggregatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Aggregator/AdjustmentsByLabelAggregator.php';

return $this->services['sylius.adjustments_aggregator'] = new \Sylius\Component\Order\Aggregator\AdjustmentsByLabelAggregator();
