<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.payment_methods_resolver' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Payment/Resolver/PaymentMethodsResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Payment/Resolver/CompositeMethodsResolver.php';

return $this->services['sylius.payment_methods_resolver'] = new \Sylius\Component\Payment\Resolver\CompositeMethodsResolver(($this->services['sylius.registry.payment_methods_resolver'] ?? $this->load('getSylius_Registry_PaymentMethodsResolverService.php')));
