<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.canonicalizer' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Canonicalizer/CanonicalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Canonicalizer/Canonicalizer.php';

return $this->services['sylius.canonicalizer'] = new \Sylius\Component\User\Canonicalizer\Canonicalizer();
