<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.state_resolver.order_checkout' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/StateResolver/StateResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/StateResolver/CheckoutStateResolver.php';

return $this->services['sylius.state_resolver.order_checkout'] = new \Sylius\Component\Core\StateResolver\CheckoutStateResolver(($this->services['sm.factory'] ?? $this->getSm_FactoryService()), ($this->services['sylius.checker.order_payment_method_selection_requirement'] ?? $this->load('getSylius_Checker_OrderPaymentMethodSelectionRequirementService.php')), ($this->services['sylius.checker.order_shipping_method_selection_requirement'] ?? $this->load('getSylius_Checker_OrderShippingMethodSelectionRequirementService.php')));
