<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.model.adapter.chain' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Model/Adapter/AdapterInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Model/Adapter/DoctrineORMAdapter.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Model/Adapter/AdapterChain.php';

$this->services['sonata.core.model.adapter.chain'] = $instance = new \Sonata\CoreBundle\Model\Adapter\AdapterChain();

$instance->addAdapter(new \Sonata\CoreBundle\Model\Adapter\DoctrineORMAdapter(($this->services['doctrine'] ?? $this->load('getDoctrineService.php'))));

return $instance;
