<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.currency_converter' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Currency/Converter/CurrencyConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Currency/Converter/CurrencyConverter.php';

return $this->services['sylius.currency_converter'] = new \Sylius\Component\Currency\Converter\CurrencyConverter(($this->services['sylius.repository.exchange_rate'] ?? $this->load('getSylius_Repository_ExchangeRateService.php')));
