<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.custom_grid_renderer.twig' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/GridBundle/Form/Registry/FormTypeRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/GridBundle/Form/Registry/FormTypeRegistry.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Grid/Renderer/GridRendererInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Grid/Renderer/TwigGridRenderer.php';

$a = ($this->services['twig'] ?? $this->load('getTwigService.php'));

if (isset($this->services['sylius.custom_grid_renderer.twig'])) {
    return $this->services['sylius.custom_grid_renderer.twig'];
}

$b = new \Sylius\Bundle\GridBundle\Form\Registry\FormTypeRegistry();
$b->add('string', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\StringFilterType');
$b->add('boolean', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\BooleanFilterType');
$b->add('date', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\DateFilterType');
$b->add('entity', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\EntityFilterType');
$b->add('money', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\MoneyFilterType');
$b->add('exists', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\ExistsFilterType');

return $this->services['sylius.custom_grid_renderer.twig'] = new \Sylius\Bundle\ResourceBundle\Grid\Renderer\TwigGridRenderer(new \Sylius\Bundle\GridBundle\Renderer\TwigGridRenderer($a, ($this->services['sylius.registry.grid_field'] ?? $this->load('getSylius_Registry_GridFieldService.php')), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), $b, 'SyliusGridBundle::_grid.html.twig', $this->parameters['sylius.grid.templates.action'], $this->parameters['sylius.grid.templates.filter']), $a, ($this->privates['sylius.grid_options_parser'] ?? $this->load('getSylius_GridOptionsParserService.php')), $this->parameters['sylius.grid.templates.action']);
