<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.currency' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php';

if ($lazyLoad) {
    return $this->services['sylius.templating.helper.currency'] = $this->createProxy('CurrencyHelper_dd0a15b', function () {
        return \CurrencyHelper_dd0a15b::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSylius_Templating_Helper_CurrencyService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Sylius\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper();
