<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.theme.locator.bundle_resource' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Locator/ResourceLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Locator/BundleResourceLocator.php';

return $this->services['sylius.theme.locator.bundle_resource'] = new \Sylius\Bundle\ThemeBundle\Locator\BundleResourceLocator(($this->services['filesystem'] ?? $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()), ($this->services['kernel'] ?? $this->get('kernel', 1)));
