<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.zone_matcher' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Matcher/ZoneMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php';

return $this->services['sylius.zone_matcher'] = new \Sylius\Component\Addressing\Matcher\ZoneMatcher(($this->services['sylius.repository.zone'] ?? $this->load('getSylius_Repository_ZoneService.php')));
