<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.theme.templating.locator.cached' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Locator/ResourceLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Locator/ResourceLocator.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Templating/Locator/TemplateLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Templating/Locator/TemplateLocator.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Templating/Locator/CachedTemplateLocator.php';

return $this->privates['sylius.theme.templating.locator.cached'] = new \Sylius\Bundle\ThemeBundle\Templating\Locator\CachedTemplateLocator(new \Sylius\Bundle\ThemeBundle\Templating\Locator\TemplateLocator(new \Sylius\Bundle\ThemeBundle\Locator\ResourceLocator(($this->services['sylius.theme.locator.application_resource'] ?? $this->load('getSylius_Theme_Locator_ApplicationResourceService.php')), ($this->services['sylius.theme.locator.bundle_resource'] ?? $this->load('getSylius_Theme_Locator_BundleResourceService.php')))), ($this->services['sylius.theme.templating.cache'] ?? $this->services['sylius.theme.templating.cache'] = new \Doctrine\Common\Cache\ArrayCache()));
