<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.shipping_methods_resolver' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Shipping/Resolver/ShippingMethodsResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Shipping/Resolver/CompositeMethodsResolver.php';

return $this->services['sylius.shipping_methods_resolver'] = new \Sylius\Component\Shipping\Resolver\CompositeMethodsResolver(($this->services['sylius.registry.shipping_methods_resolver'] ?? $this->load('getSylius_Registry_ShippingMethodsResolverService.php')));
