<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.adjustment' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Templating/Helper/AdjustmentsHelper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Aggregator/AdjustmentsAggregatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Aggregator/AdjustmentsByLabelAggregator.php';

return $this->services['sylius.templating.helper.adjustment'] = new \Sylius\Bundle\OrderBundle\Templating\Helper\AdjustmentsHelper(($this->services['sylius.adjustments_aggregator'] ?? $this->services['sylius.adjustments_aggregator'] = new \Sylius\Component\Order\Aggregator\AdjustmentsByLabelAggregator()));
