<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.theme.templating.file_locator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Config/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ThemeBundle/Templating/Locator/TemplateFileLocator.php';

return $this->privates['sylius.theme.templating.file_locator'] = new \Sylius\Bundle\ThemeBundle\Templating\Locator\TemplateFileLocator(($this->privates['sylius.theme.templating.file_locator.inner'] ?? $this->load('getSylius_Theme_Templating_FileLocator_InnerService.php')), ($this->privates['sylius.theme.context.channel_based'] ?? $this->getSylius_Theme_Context_ChannelBasedService()), ($this->privates['sylius.theme.hierarchy_provider'] ?? $this->privates['sylius.theme.hierarchy_provider'] = new \Sylius\Bundle\ThemeBundle\HierarchyProvider\ThemeHierarchyProvider()), ($this->privates['sylius.theme.templating.locator.cached'] ?? $this->load('getSylius_Theme_Templating_Locator_CachedService.php')), $this->targetDirs[0]);
