<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.locale' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Locale/Converter/LocaleConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Locale/Converter/LocaleConverter.php';

return $this->services['sylius.templating.helper.locale'] = new \Sylius\Bundle\LocaleBundle\Templating\Helper\LocaleHelper(($this->services['sylius.locale_converter'] ?? $this->services['sylius.locale_converter'] = new \Sylius\Component\Locale\Converter\LocaleConverter()));
