<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/EngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/StreamingEngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/EngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php';

$a = ($this->services['twig'] ?? $this->load('getTwigService.php'));

if (isset($this->services['templating'])) {
    return $this->services['templating'];
}

return $this->services['templating'] = new \Symfony\Bundle\TwigBundle\TwigEngine($a, ($this->privates['sylius.theme.templating.name_parser'] ?? $this->load('getSylius_Theme_Templating_NameParserService.php')), ($this->privates['sylius.theme.templating.file_locator'] ?? $this->load('getSylius_Theme_Templating_FileLocatorService.php')));
