<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.validator_factory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ContainerConstraintValidatorFactory.php';

return $this->privates['validator.validator_factory'] = new \Symfony\Component\Validator\ContainerConstraintValidatorFactory(new \Symfony\Component\DependencyInjection\ServiceLocator(array('Sonata\\CoreBundle\\Validator\\InlineValidator' => function () {
    return ($this->privates['sonata.core.validator.inline'] ?? $this->load('getSonata_Core_Validator_InlineService.php'));
}, 'Sylius\\Bundle\\AddressingBundle\\Validator\\Constraints\\ProvinceAddressConstraintValidator' => function () {
    return ($this->services['sylius.validator.valid_province_address'] ?? $this->load('getSylius_Validator_ValidProvinceAddressService.php'));
}, 'Sylius\\Bundle\\AttributeBundle\\Validator\\Constraints\\ValidAttributeValueValidator' => function () {
    return ($this->services['sylius.validator.valid_attribute_value'] ?? $this->load('getSylius_Validator_ValidAttributeValueService.php'));
}, 'Sylius\\Bundle\\AttributeBundle\\Validator\\Constraints\\ValidSelectAttributeConfigurationValidator' => function () {
    return ($this->services['sylius.validator.valid_select_attribute'] ?? $this->services['sylius.validator.valid_select_attribute'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidSelectAttributeConfigurationValidator());
}, 'Sylius\\Bundle\\AttributeBundle\\Validator\\Constraints\\ValidTextAttributeConfigurationValidator' => function () {
    return ($this->services['sylius.validator.valid_text_attribute'] ?? $this->services['sylius.validator.valid_text_attribute'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidTextAttributeConfigurationValidator());
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\CartItemAvailabilityValidator' => function () {
    return ($this->services['sylius.validator.cart_item_availability'] ?? $this->load('getSylius_Validator_CartItemAvailabilityService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\HasAllPricesDefinedValidator' => function () {
    return ($this->services['sylius.validator.has_all_prices_defined'] ?? $this->services['sylius.validator.has_all_prices_defined'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\HasAllPricesDefinedValidator());
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\HasAllVariantPricesDefinedValidator' => function () {
    return ($this->services['sylius.validator.has_all_variant_prices_defined'] ?? $this->services['sylius.validator.has_all_variant_prices_defined'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\HasAllVariantPricesDefinedValidator());
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\HasEnabledEntityValidator' => function () {
    return ($this->services['sylius.validator.has_enabled_entity'] ?? $this->load('getSylius_Validator_HasEnabledEntityService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\LocalesAwareValidAttributeValueValidator' => function () {
    return ($this->services['sylius.validator.locales_aware_valid_attribute_value'] ?? $this->load('getSylius_Validator_LocalesAwareValidAttributeValueService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\OrderPaymentMethodEligibilityValidator' => function () {
    return ($this->services['sylius.validator.payment_method_integrity'] ?? $this->services['sylius.validator.payment_method_integrity'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderPaymentMethodEligibilityValidator());
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\OrderProductEligibilityValidator' => function () {
    return ($this->services['sylius.validator.product_integrity'] ?? $this->services['sylius.validator.product_integrity'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderProductEligibilityValidator());
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\OrderShippingMethodEligibilityValidator' => function () {
    return ($this->services['sylius.validator.shipping_method_integrity'] ?? $this->load('getSylius_Validator_ShippingMethodIntegrityService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\RegisteredUserValidator' => function () {
    return ($this->services['sylius.validator.unique.registered_user'] ?? $this->load('getSylius_Validator_Unique_RegisteredUserService.php'));
}, 'Sylius\\Bundle\\CoreBundle\\Validator\\Constraints\\UniqueReviewerEmailValidator' => function () {
    return ($this->services['sylius.validator.unique_reviewer_email'] ?? $this->load('getSylius_Validator_UniqueReviewerEmailService.php'));
}, 'Sylius\\Bundle\\CurrencyBundle\\Validator\\Constraints\\DifferentSourceTargetCurrencyValidator' => function () {
    return ($this->services['sylius.validator.different_source_target_currency'] ?? $this->services['sylius.validator.different_source_target_currency'] = new \Sylius\Bundle\CurrencyBundle\Validator\Constraints\DifferentSourceTargetCurrencyValidator());
}, 'Sylius\\Bundle\\CurrencyBundle\\Validator\\Constraints\\UniqueCurrencyPairValidator' => function () {
    return ($this->services['sylius.validator.unique_currency_pair'] ?? $this->load('getSylius_Validator_UniqueCurrencyPairService.php'));
}, 'Sylius\\Bundle\\InventoryBundle\\Validator\\Constraints\\InStockValidator' => function () {
    return ($this->services['sylius.validator.in_stock'] ?? $this->load('getSylius_Validator_InStockService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Validator\\ProductVariantCombinationValidator' => function () {
    return ($this->services['sylius.validator.product_variant_combination'] ?? $this->load('getSylius_Validator_ProductVariantCombinationService.php'));
}, 'Sylius\\Bundle\\ProductBundle\\Validator\\UniqueSimpleProductCodeValidator' => function () {
    return ($this->services['sylius.validator.product_code_uniqueness'] ?? $this->load('getSylius_Validator_ProductCodeUniquenessService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Validator\\CouponGenerationAmountValidator' => function () {
    return ($this->services['sylius.validator.promotion_coupon_generation_amount'] ?? $this->load('getSylius_Validator_PromotionCouponGenerationAmountService.php'));
}, 'Sylius\\Bundle\\PromotionBundle\\Validator\\PromotionDateRangeValidator' => function () {
    return ($this->services['sylius.validator.date_range'] ?? $this->services['sylius.validator.date_range'] = new \Sylius\Bundle\PromotionBundle\Validator\PromotionDateRangeValidator());
}, 'Sylius\\Bundle\\PromotionBundle\\Validator\\PromotionSubjectCouponValidator' => function () {
    return ($this->services['sylius.validator.promotion_subject_coupon'] ?? $this->load('getSylius_Validator_PromotionSubjectCouponService.php'));
}, 'Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntityValidator' => function () {
    return ($this->privates['doctrine.orm.validator.unique'] ?? $this->load('getDoctrine_Orm_Validator_UniqueService.php'));
}, 'Symfony\\Component\\Security\\Core\\Validator\\Constraints\\UserPasswordValidator' => function () {
    return ($this->privates['security.validator.user_password'] ?? $this->load('getSecurity_Validator_UserPasswordService.php'));
}, 'Symfony\\Component\\Validator\\Constraints\\EmailValidator' => function () {
    return ($this->privates['validator.email'] ?? $this->privates['validator.email'] = new \Symfony\Component\Validator\Constraints\EmailValidator('loose'));
}, 'Symfony\\Component\\Validator\\Constraints\\ExpressionValidator' => function () {
    return ($this->privates['validator.expression'] ?? $this->privates['validator.expression'] = new \Symfony\Component\Validator\Constraints\ExpressionValidator());
}, 'doctrine.orm.validator.unique' => function () {
    return ($this->privates['doctrine.orm.validator.unique'] ?? $this->load('getDoctrine_Orm_Validator_UniqueService.php'));
}, 'registered_user_validator' => function () {
    return ($this->services['sylius.validator.unique.registered_user'] ?? $this->load('getSylius_Validator_Unique_RegisteredUserService.php'));
}, 'security.validator.user_password' => function () {
    return ($this->privates['security.validator.user_password'] ?? $this->load('getSecurity_Validator_UserPasswordService.php'));
}, 'sonata.core.validator.inline' => function () {
    return ($this->privates['sonata.core.validator.inline'] ?? $this->load('getSonata_Core_Validator_InlineService.php'));
}, 'sylius.validator.product_variant_combination' => function () {
    return ($this->services['sylius.validator.product_variant_combination'] ?? $this->load('getSylius_Validator_ProductVariantCombinationService.php'));
}, 'sylius.validator.unique_simple_product_code' => function () {
    return ($this->services['sylius.validator.product_code_uniqueness'] ?? $this->load('getSylius_Validator_ProductCodeUniquenessService.php'));
}, 'sylius_cart_item_availability' => function () {
    return ($this->services['sylius.validator.cart_item_availability'] ?? $this->load('getSylius_Validator_CartItemAvailabilityService.php'));
}, 'sylius_coupon_generation_amount_validator' => function () {
    return ($this->services['sylius.validator.promotion_coupon_generation_amount'] ?? $this->load('getSylius_Validator_PromotionCouponGenerationAmountService.php'));
}, 'sylius_has_all_prices_defined' => function () {
    return ($this->services['sylius.validator.has_all_prices_defined'] ?? $this->services['sylius.validator.has_all_prices_defined'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\HasAllPricesDefinedValidator());
}, 'sylius_has_all_variant_prices_defined' => function () {
    return ($this->services['sylius.validator.has_all_variant_prices_defined'] ?? $this->services['sylius.validator.has_all_variant_prices_defined'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\HasAllVariantPricesDefinedValidator());
}, 'sylius_has_enabled_entity' => function () {
    return ($this->services['sylius.validator.has_enabled_entity'] ?? $this->load('getSylius_Validator_HasEnabledEntityService.php'));
}, 'sylius_in_stock' => function () {
    return ($this->services['sylius.validator.in_stock'] ?? $this->load('getSylius_Validator_InStockService.php'));
}, 'sylius_order_payment_method_eligibility_validator' => function () {
    return ($this->services['sylius.validator.payment_method_integrity'] ?? $this->services['sylius.validator.payment_method_integrity'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderPaymentMethodEligibilityValidator());
}, 'sylius_order_product_eligibility_validator' => function () {
    return ($this->services['sylius.validator.product_integrity'] ?? $this->services['sylius.validator.product_integrity'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderProductEligibilityValidator());
}, 'sylius_order_shipping_method_eligibility_validator' => function () {
    return ($this->services['sylius.validator.shipping_method_integrity'] ?? $this->load('getSylius_Validator_ShippingMethodIntegrityService.php'));
}, 'sylius_promotion_date_range_validator' => function () {
    return ($this->services['sylius.validator.date_range'] ?? $this->services['sylius.validator.date_range'] = new \Sylius\Bundle\PromotionBundle\Validator\PromotionDateRangeValidator());
}, 'sylius_promotion_subject_validator' => function () {
    return ($this->services['sylius.validator.promotion_subject_coupon'] ?? $this->load('getSylius_Validator_PromotionSubjectCouponService.php'));
}, 'sylius_province_address_validator' => function () {
    return ($this->services['sylius.validator.valid_province_address'] ?? $this->load('getSylius_Validator_ValidProvinceAddressService.php'));
}, 'sylius_unique_reviewer_email_validator' => function () {
    return ($this->services['sylius.validator.unique_reviewer_email'] ?? $this->load('getSylius_Validator_UniqueReviewerEmailService.php'));
}, 'sylius_valid_attribute_value_validator' => function () {
    return ($this->services['sylius.validator.locales_aware_valid_attribute_value'] ?? $this->load('getSylius_Validator_LocalesAwareValidAttributeValueService.php'));
}, 'sylius_valid_select_attribute_validator' => function () {
    return ($this->services['sylius.validator.valid_select_attribute'] ?? $this->services['sylius.validator.valid_select_attribute'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidSelectAttributeConfigurationValidator());
}, 'sylius_valid_text_attribute_validator' => function () {
    return ($this->services['sylius.validator.valid_text_attribute'] ?? $this->services['sylius.validator.valid_text_attribute'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidTextAttributeConfigurationValidator());
}, 'validator.expression' => function () {
    return ($this->privates['validator.expression'] ?? $this->privates['validator.expression'] = new \Symfony\Component\Validator\Constraints\ExpressionValidator());
})));
