<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB2xhV27\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB2xhV27/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerB2xhV27.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerB2xhV27\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerB2xhV27\appProdDebugProjectContainer(array(
    'container.build_hash' => 'B2xhV27',
    'container.build_id' => '7403fa28',
    'container.build_time' => 1540841399,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerB2xhV27');
