<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ump1bk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ump1bk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0ump1bk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0ump1bk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0ump1bk\appDevDebugProjectContainer(array(
    'container.build_hash' => '0ump1bk',
    'container.build_id' => 'a6a21e33',
    'container.build_time' => 1540576162,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0ump1bk');
